name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: false
        description: The environment in which to deploy
        default: Sandbox
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: The environment in which to deploy
        default: Sandbox
        type: choice
        options:
          - Sandbox
          - Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.DEPLOYMENT_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.SSHKEY_PASSPHRASE }}
          script: 'source "${{ secrets.REMOTE_USER_BASHRC }}" && cd "${{ secrets.REMOTE_PROJECT_LOCATION }}" && ./.scripts/deploy.sh'

